# Generated by Django 4.2.18 on 2025-01-17 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workapp',
            name='mobilephone',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='workapp',
            name='startDate',
            field=models.DateField(null=True),
        ),
    ]
